package com.liferay.portlet.asset.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.liferay.portlet.asset.model.AssetTag;
import com.liferay.portlet.asset.service.AssetTagLocalServiceUtil;

/**
 * The extended model base implementation for the AssetTag service. Represents a row in the &quot;AssetTag&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AssetTagImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AssetTagImpl
 * @see com.liferay.portlet.asset.model.AssetTag
 * @generated
 */
public abstract class AssetTagBaseImpl extends AssetTagModelImpl
    implements AssetTag {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a asset tag model instance should use the {@link AssetTag} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            AssetTagLocalServiceUtil.addAssetTag(this);
        } else {
            AssetTagLocalServiceUtil.updateAssetTag(this);
        }
    }
}
