package com.liferay.portlet.asset.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.liferay.portlet.asset.model.AssetCategory;
import com.liferay.portlet.asset.service.AssetCategoryLocalServiceUtil;

/**
 * The extended model base implementation for the AssetCategory service. Represents a row in the &quot;AssetCategory&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AssetCategoryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AssetCategoryImpl
 * @see com.liferay.portlet.asset.model.AssetCategory
 * @generated
 */
public abstract class AssetCategoryBaseImpl extends AssetCategoryModelImpl
    implements AssetCategory {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a asset category model instance should use the {@link AssetCategory} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            AssetCategoryLocalServiceUtil.addAssetCategory(this);
        } else {
            AssetCategoryLocalServiceUtil.updateAssetCategory(this);
        }
    }
}
