package com.liferay.mail.service.base;

import com.liferay.mail.service.MailService;
import com.liferay.mail.service.persistence.CyrusUserPersistence;
import com.liferay.mail.service.persistence.CyrusVirtualPersistence;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.InfrastructureUtil;
import com.liferay.portal.service.BaseServiceImpl;
import com.liferay.portal.service.persistence.UserFinder;
import com.liferay.portal.service.persistence.UserPersistence;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the mail remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.mail.service.impl.MailServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.mail.service.impl.MailServiceImpl
 * @see com.liferay.mail.service.MailServiceUtil
 * @generated
 */
public abstract class MailServiceBaseImpl extends BaseServiceImpl
    implements MailService, IdentifiableBean {
    @BeanReference(type = com.liferay.mail.service.CyrusService.class)
    protected com.liferay.mail.service.CyrusService cyrusService;
    @BeanReference(type = com.liferay.mail.service.CyrusUserService.class)
    protected com.liferay.mail.service.CyrusUserService cyrusUserService;
    @BeanReference(type = CyrusUserPersistence.class)
    protected CyrusUserPersistence cyrusUserPersistence;
    @BeanReference(type = com.liferay.mail.service.CyrusVirtualLocalService.class)
    protected com.liferay.mail.service.CyrusVirtualLocalService cyrusVirtualLocalService;
    @BeanReference(type = CyrusVirtualPersistence.class)
    protected CyrusVirtualPersistence cyrusVirtualPersistence;
    @BeanReference(type = com.liferay.mail.service.MailService.class)
    protected com.liferay.mail.service.MailService mailService;
    @BeanReference(type = com.liferay.counter.service.CounterLocalService.class)
    protected com.liferay.counter.service.CounterLocalService counterLocalService;
    @BeanReference(type = com.liferay.portal.service.ResourceLocalService.class)
    protected com.liferay.portal.service.ResourceLocalService resourceLocalService;
    @BeanReference(type = com.liferay.portal.service.UserLocalService.class)
    protected com.liferay.portal.service.UserLocalService userLocalService;
    @BeanReference(type = com.liferay.portal.service.UserService.class)
    protected com.liferay.portal.service.UserService userService;
    @BeanReference(type = UserPersistence.class)
    protected UserPersistence userPersistence;
    @BeanReference(type = UserFinder.class)
    protected UserFinder userFinder;
    private String _beanIdentifier;

    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. Always use {@link com.liferay.mail.service.MailServiceUtil} to access the mail remote service.
     */

    /**
     * Returns the cyrus remote service.
     *
     * @return the cyrus remote service
     */
    public com.liferay.mail.service.CyrusService getCyrusService() {
        return cyrusService;
    }

    /**
     * Sets the cyrus remote service.
     *
     * @param cyrusService the cyrus remote service
     */
    public void setCyrusService(
        com.liferay.mail.service.CyrusService cyrusService) {
        this.cyrusService = cyrusService;
    }

    /**
     * Returns the cyrus user remote service.
     *
     * @return the cyrus user remote service
     */
    public com.liferay.mail.service.CyrusUserService getCyrusUserService() {
        return cyrusUserService;
    }

    /**
     * Sets the cyrus user remote service.
     *
     * @param cyrusUserService the cyrus user remote service
     */
    public void setCyrusUserService(
        com.liferay.mail.service.CyrusUserService cyrusUserService) {
        this.cyrusUserService = cyrusUserService;
    }

    /**
     * Returns the cyrus user persistence.
     *
     * @return the cyrus user persistence
     */
    public CyrusUserPersistence getCyrusUserPersistence() {
        return cyrusUserPersistence;
    }

    /**
     * Sets the cyrus user persistence.
     *
     * @param cyrusUserPersistence the cyrus user persistence
     */
    public void setCyrusUserPersistence(
        CyrusUserPersistence cyrusUserPersistence) {
        this.cyrusUserPersistence = cyrusUserPersistence;
    }

    /**
     * Returns the cyrus virtual local service.
     *
     * @return the cyrus virtual local service
     */
    public com.liferay.mail.service.CyrusVirtualLocalService getCyrusVirtualLocalService() {
        return cyrusVirtualLocalService;
    }

    /**
     * Sets the cyrus virtual local service.
     *
     * @param cyrusVirtualLocalService the cyrus virtual local service
     */
    public void setCyrusVirtualLocalService(
        com.liferay.mail.service.CyrusVirtualLocalService cyrusVirtualLocalService) {
        this.cyrusVirtualLocalService = cyrusVirtualLocalService;
    }

    /**
     * Returns the cyrus virtual persistence.
     *
     * @return the cyrus virtual persistence
     */
    public CyrusVirtualPersistence getCyrusVirtualPersistence() {
        return cyrusVirtualPersistence;
    }

    /**
     * Sets the cyrus virtual persistence.
     *
     * @param cyrusVirtualPersistence the cyrus virtual persistence
     */
    public void setCyrusVirtualPersistence(
        CyrusVirtualPersistence cyrusVirtualPersistence) {
        this.cyrusVirtualPersistence = cyrusVirtualPersistence;
    }

    /**
     * Returns the mail remote service.
     *
     * @return the mail remote service
     */
    public com.liferay.mail.service.MailService getMailService() {
        return mailService;
    }

    /**
     * Sets the mail remote service.
     *
     * @param mailService the mail remote service
     */
    public void setMailService(com.liferay.mail.service.MailService mailService) {
        this.mailService = mailService;
    }

    /**
     * Returns the counter local service.
     *
     * @return the counter local service
     */
    public com.liferay.counter.service.CounterLocalService getCounterLocalService() {
        return counterLocalService;
    }

    /**
     * Sets the counter local service.
     *
     * @param counterLocalService the counter local service
     */
    public void setCounterLocalService(
        com.liferay.counter.service.CounterLocalService counterLocalService) {
        this.counterLocalService = counterLocalService;
    }

    /**
     * Returns the resource local service.
     *
     * @return the resource local service
     */
    public com.liferay.portal.service.ResourceLocalService getResourceLocalService() {
        return resourceLocalService;
    }

    /**
     * Sets the resource local service.
     *
     * @param resourceLocalService the resource local service
     */
    public void setResourceLocalService(
        com.liferay.portal.service.ResourceLocalService resourceLocalService) {
        this.resourceLocalService = resourceLocalService;
    }

    /**
     * Returns the user local service.
     *
     * @return the user local service
     */
    public com.liferay.portal.service.UserLocalService getUserLocalService() {
        return userLocalService;
    }

    /**
     * Sets the user local service.
     *
     * @param userLocalService the user local service
     */
    public void setUserLocalService(
        com.liferay.portal.service.UserLocalService userLocalService) {
        this.userLocalService = userLocalService;
    }

    /**
     * Returns the user remote service.
     *
     * @return the user remote service
     */
    public com.liferay.portal.service.UserService getUserService() {
        return userService;
    }

    /**
     * Sets the user remote service.
     *
     * @param userService the user remote service
     */
    public void setUserService(
        com.liferay.portal.service.UserService userService) {
        this.userService = userService;
    }

    /**
     * Returns the user persistence.
     *
     * @return the user persistence
     */
    public UserPersistence getUserPersistence() {
        return userPersistence;
    }

    /**
     * Sets the user persistence.
     *
     * @param userPersistence the user persistence
     */
    public void setUserPersistence(UserPersistence userPersistence) {
        this.userPersistence = userPersistence;
    }

    /**
     * Returns the user finder.
     *
     * @return the user finder
     */
    public UserFinder getUserFinder() {
        return userFinder;
    }

    /**
     * Sets the user finder.
     *
     * @param userFinder the user finder
     */
    public void setUserFinder(UserFinder userFinder) {
        this.userFinder = userFinder;
    }

    public void afterPropertiesSet() {
    }

    public void destroy() {
    }

    /**
     * Returns the Spring bean ID for this bean.
     *
     * @return the Spring bean ID for this bean
     */
    @Override
    public String getBeanIdentifier() {
        return _beanIdentifier;
    }

    /**
     * Sets the Spring bean ID for this bean.
     *
     * @param beanIdentifier the Spring bean ID for this bean
     */
    @Override
    public void setBeanIdentifier(String beanIdentifier) {
        _beanIdentifier = beanIdentifier;
    }

    /**
     * Performs an SQL query.
     *
     * @param sql the sql query
     */
    protected void runSQL(String sql) throws SystemException {
        try {
            DataSource dataSource = InfrastructureUtil.getDataSource();

            SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
                    sql, new int[0]);

            sqlUpdate.update();
        } catch (Exception e) {
            throw new SystemException(e);
        }
    }
}
