package com.liferay.portlet.dynamicdatalists.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.liferay.portlet.dynamicdatalists.model.DDLRecordSet;
import com.liferay.portlet.dynamicdatalists.service.DDLRecordSetLocalServiceUtil;

/**
 * The extended model base implementation for the DDLRecordSet service. Represents a row in the &quot;DDLRecordSet&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DDLRecordSetImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DDLRecordSetImpl
 * @see com.liferay.portlet.dynamicdatalists.model.DDLRecordSet
 * @generated
 */
public abstract class DDLRecordSetBaseImpl extends DDLRecordSetModelImpl
    implements DDLRecordSet {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a d d l record set model instance should use the {@link DDLRecordSet} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            DDLRecordSetLocalServiceUtil.addDDLRecordSet(this);
        } else {
            DDLRecordSetLocalServiceUtil.updateDDLRecordSet(this);
        }
    }
}
