package com.liferay.portlet.dynamicdatalists.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.liferay.portlet.dynamicdatalists.model.DDLRecord;
import com.liferay.portlet.dynamicdatalists.service.DDLRecordLocalServiceUtil;

/**
 * The extended model base implementation for the DDLRecord service. Represents a row in the &quot;DDLRecord&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DDLRecordImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DDLRecordImpl
 * @see com.liferay.portlet.dynamicdatalists.model.DDLRecord
 * @generated
 */
public abstract class DDLRecordBaseImpl extends DDLRecordModelImpl
    implements DDLRecord {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a d d l record model instance should use the {@link DDLRecord} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            DDLRecordLocalServiceUtil.addDDLRecord(this);
        } else {
            DDLRecordLocalServiceUtil.updateDDLRecord(this);
        }
    }
}
