/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portal.ext.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.AttachedModel;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ModelConnectionLine service. Represents a row in the &quot;ModelConnectionLine&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.portal.ext.model.impl.ModelConnectionLineModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.portal.ext.model.impl.ModelConnectionLineImpl}.
 * </p>
 *
 * @author Jeff Qian
 * @see ModelConnectionLine
 * @see com.liferay.portal.ext.model.impl.ModelConnectionLineImpl
 * @see com.liferay.portal.ext.model.impl.ModelConnectionLineModelImpl
 * @generated
 */
@ProviderType
public interface ModelConnectionLineModel extends AttachedModel,
	BaseModel<ModelConnectionLine> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a model connection line model instance should use the {@link ModelConnectionLine} interface instead.
	 */

	/**
	 * Returns the primary key of this model connection line.
	 *
	 * @return the primary key of this model connection line
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this model connection line.
	 *
	 * @param primaryKey the primary key of this model connection line
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the line ID of this model connection line.
	 *
	 * @return the line ID of this model connection line
	 */
	public long getLineId();

	/**
	 * Sets the line ID of this model connection line.
	 *
	 * @param lineId the line ID of this model connection line
	 */
	public void setLineId(long lineId);

	/**
	 * Returns the user ID of this model connection line.
	 *
	 * @return the user ID of this model connection line
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this model connection line.
	 *
	 * @param userId the user ID of this model connection line
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this model connection line.
	 *
	 * @return the user uuid of this model connection line
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this model connection line.
	 *
	 * @param userUuid the user uuid of this model connection line
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this model connection line.
	 *
	 * @return the user name of this model connection line
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this model connection line.
	 *
	 * @param userName the user name of this model connection line
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create date of this model connection line.
	 *
	 * @return the create date of this model connection line
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this model connection line.
	 *
	 * @param createDate the create date of this model connection line
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this model connection line.
	 *
	 * @return the modified date of this model connection line
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this model connection line.
	 *
	 * @param modifiedDate the modified date of this model connection line
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the line group ID of this model connection line.
	 *
	 * @return the line group ID of this model connection line
	 */
	public long getLineGroupId();

	/**
	 * Sets the line group ID of this model connection line.
	 *
	 * @param lineGroupId the line group ID of this model connection line
	 */
	public void setLineGroupId(long lineGroupId);

	/**
	 * Returns the fully qualified class name of this model connection line.
	 *
	 * @return the fully qualified class name of this model connection line
	 */
	@Override
	public String getClassName();

	public void setClassName(String className);

	/**
	 * Returns the class name ID of this model connection line.
	 *
	 * @return the class name ID of this model connection line
	 */
	@Override
	public long getClassNameId();

	/**
	 * Sets the class name ID of this model connection line.
	 *
	 * @param classNameId the class name ID of this model connection line
	 */
	@Override
	public void setClassNameId(long classNameId);

	/**
	 * Returns the class p k of this model connection line.
	 *
	 * @return the class p k of this model connection line
	 */
	@Override
	public long getClassPK();

	/**
	 * Sets the class p k of this model connection line.
	 *
	 * @param classPK the class p k of this model connection line
	 */
	@Override
	public void setClassPK(long classPK);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.liferay.portal.ext.model.ModelConnectionLine modelConnectionLine);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.liferay.portal.ext.model.ModelConnectionLine> toCacheModel();

	@Override
	public com.liferay.portal.ext.model.ModelConnectionLine toEscapedModel();

	@Override
	public com.liferay.portal.ext.model.ModelConnectionLine toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}