/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portal.ext.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ServiceTag service. Represents a row in the &quot;ServiceTag&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.portal.ext.model.impl.ServiceTagModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.portal.ext.model.impl.ServiceTagImpl}.
 * </p>
 *
 * @author Jeff Qian
 * @see ServiceTag
 * @see com.liferay.portal.ext.model.impl.ServiceTagImpl
 * @see com.liferay.portal.ext.model.impl.ServiceTagModelImpl
 * @generated
 */
@ProviderType
public interface ServiceTagModel extends BaseModel<ServiceTag> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a service tag model instance should use the {@link ServiceTag} interface instead.
	 */

	/**
	 * Returns the primary key of this service tag.
	 *
	 * @return the primary key of this service tag
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this service tag.
	 *
	 * @param primaryKey the primary key of this service tag
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the tag ID of this service tag.
	 *
	 * @return the tag ID of this service tag
	 */
	public long getTagId();

	/**
	 * Sets the tag ID of this service tag.
	 *
	 * @param tagId the tag ID of this service tag
	 */
	public void setTagId(long tagId);

	/**
	 * Returns the user ID of this service tag.
	 *
	 * @return the user ID of this service tag
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this service tag.
	 *
	 * @param userId the user ID of this service tag
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this service tag.
	 *
	 * @return the user uuid of this service tag
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this service tag.
	 *
	 * @param userUuid the user uuid of this service tag
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this service tag.
	 *
	 * @return the user name of this service tag
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this service tag.
	 *
	 * @param userName the user name of this service tag
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create date of this service tag.
	 *
	 * @return the create date of this service tag
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this service tag.
	 *
	 * @param createDate the create date of this service tag
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this service tag.
	 *
	 * @return the modified date of this service tag
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this service tag.
	 *
	 * @param modifiedDate the modified date of this service tag
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the tag name of this service tag.
	 *
	 * @return the tag name of this service tag
	 */
	@AutoEscape
	public String getTagName();

	/**
	 * Sets the tag name of this service tag.
	 *
	 * @param tagName the tag name of this service tag
	 */
	public void setTagName(String tagName);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.liferay.portal.ext.model.ServiceTag serviceTag);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.liferay.portal.ext.model.ServiceTag> toCacheModel();

	@Override
	public com.liferay.portal.ext.model.ServiceTag toEscapedModel();

	@Override
	public com.liferay.portal.ext.model.ServiceTag toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}