/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portal.ext.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ServiceHost service. Represents a row in the &quot;ServiceHost&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.portal.ext.model.impl.ServiceHostModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.portal.ext.model.impl.ServiceHostImpl}.
 * </p>
 *
 * @author Jeff Qian
 * @see ServiceHost
 * @see com.liferay.portal.ext.model.impl.ServiceHostImpl
 * @see com.liferay.portal.ext.model.impl.ServiceHostModelImpl
 * @generated
 */
@ProviderType
public interface ServiceHostModel extends BaseModel<ServiceHost> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a service host model instance should use the {@link ServiceHost} interface instead.
	 */

	/**
	 * Returns the primary key of this service host.
	 *
	 * @return the primary key of this service host
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this service host.
	 *
	 * @param primaryKey the primary key of this service host
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the host ID of this service host.
	 *
	 * @return the host ID of this service host
	 */
	public long getHostId();

	/**
	 * Sets the host ID of this service host.
	 *
	 * @param hostId the host ID of this service host
	 */
	public void setHostId(long hostId);

	/**
	 * Returns the code of this service host.
	 *
	 * @return the code of this service host
	 */
	@AutoEscape
	public String getCode();

	/**
	 * Sets the code of this service host.
	 *
	 * @param code the code of this service host
	 */
	public void setCode(String code);

	/**
	 * Returns the user ID of this service host.
	 *
	 * @return the user ID of this service host
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this service host.
	 *
	 * @param userId the user ID of this service host
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this service host.
	 *
	 * @return the user uuid of this service host
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this service host.
	 *
	 * @param userUuid the user uuid of this service host
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this service host.
	 *
	 * @return the user name of this service host
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this service host.
	 *
	 * @param userName the user name of this service host
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create date of this service host.
	 *
	 * @return the create date of this service host
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this service host.
	 *
	 * @param createDate the create date of this service host
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this service host.
	 *
	 * @return the modified date of this service host
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this service host.
	 *
	 * @param modifiedDate the modified date of this service host
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the address of this service host.
	 *
	 * @return the address of this service host
	 */
	@AutoEscape
	public String getAddress();

	/**
	 * Sets the address of this service host.
	 *
	 * @param address the address of this service host
	 */
	public void setAddress(String address);

	/**
	 * Returns the protocol of this service host.
	 *
	 * @return the protocol of this service host
	 */
	@AutoEscape
	public String getProtocol();

	/**
	 * Sets the protocol of this service host.
	 *
	 * @param protocol the protocol of this service host
	 */
	public void setProtocol(String protocol);

	/**
	 * Returns the port of this service host.
	 *
	 * @return the port of this service host
	 */
	public int getPort();

	/**
	 * Sets the port of this service host.
	 *
	 * @param port the port of this service host
	 */
	public void setPort(int port);

	/**
	 * Returns the proxy host of this service host.
	 *
	 * @return the proxy host of this service host
	 */
	@AutoEscape
	public String getProxyHost();

	/**
	 * Sets the proxy host of this service host.
	 *
	 * @param proxyHost the proxy host of this service host
	 */
	public void setProxyHost(String proxyHost);

	/**
	 * Returns the proxy port of this service host.
	 *
	 * @return the proxy port of this service host
	 */
	public int getProxyPort();

	/**
	 * Sets the proxy port of this service host.
	 *
	 * @param proxyPort the proxy port of this service host
	 */
	public void setProxyPort(int proxyPort);

	/**
	 * Returns the proxy user name of this service host.
	 *
	 * @return the proxy user name of this service host
	 */
	@AutoEscape
	public String getProxyUserName();

	/**
	 * Sets the proxy user name of this service host.
	 *
	 * @param proxyUserName the proxy user name of this service host
	 */
	public void setProxyUserName(String proxyUserName);

	/**
	 * Returns the proxy password of this service host.
	 *
	 * @return the proxy password of this service host
	 */
	@AutoEscape
	public String getProxyPassword();

	/**
	 * Sets the proxy password of this service host.
	 *
	 * @param proxyPassword the proxy password of this service host
	 */
	public void setProxyPassword(String proxyPassword);

	/**
	 * Returns the proxy auth type of this service host.
	 *
	 * @return the proxy auth type of this service host
	 */
	@AutoEscape
	public String getProxyAuthType();

	/**
	 * Sets the proxy auth type of this service host.
	 *
	 * @param proxyAuthType the proxy auth type of this service host
	 */
	public void setProxyAuthType(String proxyAuthType);

	/**
	 * Returns the cache response of this service host.
	 *
	 * @return the cache response of this service host
	 */
	public boolean getCacheResponse();

	/**
	 * Returns <code>true</code> if this service host is cache response.
	 *
	 * @return <code>true</code> if this service host is cache response; <code>false</code> otherwise
	 */
	public boolean isCacheResponse();

	/**
	 * Sets whether this service host is cache response.
	 *
	 * @param cacheResponse the cache response of this service host
	 */
	public void setCacheResponse(boolean cacheResponse);

	/**
	 * Returns the max connections per host of this service host.
	 *
	 * @return the max connections per host of this service host
	 */
	public int getMaxConnectionsPerHost();

	/**
	 * Sets the max connections per host of this service host.
	 *
	 * @param maxConnectionsPerHost the max connections per host of this service host
	 */
	public void setMaxConnectionsPerHost(int maxConnectionsPerHost);

	/**
	 * Returns the timeout of this service host.
	 *
	 * @return the timeout of this service host
	 */
	public int getTimeout();

	/**
	 * Sets the timeout of this service host.
	 *
	 * @param timeout the timeout of this service host
	 */
	public void setTimeout(int timeout);

	/**
	 * Returns the session cookie use full host name of this service host.
	 *
	 * @return the session cookie use full host name of this service host
	 */
	public boolean getSessionCookieUseFullHostName();

	/**
	 * Returns <code>true</code> if this service host is session cookie use full host name.
	 *
	 * @return <code>true</code> if this service host is session cookie use full host name; <code>false</code> otherwise
	 */
	public boolean isSessionCookieUseFullHostName();

	/**
	 * Sets whether this service host is session cookie use full host name.
	 *
	 * @param sessionCookieUseFullHostName the session cookie use full host name of this service host
	 */
	public void setSessionCookieUseFullHostName(
		boolean sessionCookieUseFullHostName);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.liferay.portal.ext.model.ServiceHost serviceHost);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.liferay.portal.ext.model.ServiceHost> toCacheModel();

	@Override
	public com.liferay.portal.ext.model.ServiceHost toEscapedModel();

	@Override
	public com.liferay.portal.ext.model.ServiceHost toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}