/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portal.ext.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.AttachedModel;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ServiceHistory service. Represents a row in the &quot;ServiceHistory&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.portal.ext.model.impl.ServiceHistoryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.portal.ext.model.impl.ServiceHistoryImpl}.
 * </p>
 *
 * @author Jeff Qian
 * @see ServiceHistory
 * @see com.liferay.portal.ext.model.impl.ServiceHistoryImpl
 * @see com.liferay.portal.ext.model.impl.ServiceHistoryModelImpl
 * @generated
 */
@ProviderType
public interface ServiceHistoryModel extends AttachedModel,
	BaseModel<ServiceHistory> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a service history model instance should use the {@link ServiceHistory} interface instead.
	 */

	/**
	 * Returns the primary key of this service history.
	 *
	 * @return the primary key of this service history
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this service history.
	 *
	 * @param primaryKey the primary key of this service history
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the his ID of this service history.
	 *
	 * @return the his ID of this service history
	 */
	public long getHisId();

	/**
	 * Sets the his ID of this service history.
	 *
	 * @param hisId the his ID of this service history
	 */
	public void setHisId(long hisId);

	/**
	 * Returns the user ID of this service history.
	 *
	 * @return the user ID of this service history
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this service history.
	 *
	 * @param userId the user ID of this service history
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this service history.
	 *
	 * @return the user uuid of this service history
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this service history.
	 *
	 * @param userUuid the user uuid of this service history
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this service history.
	 *
	 * @return the user name of this service history
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this service history.
	 *
	 * @param userName the user name of this service history
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create date of this service history.
	 *
	 * @return the create date of this service history
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this service history.
	 *
	 * @param createDate the create date of this service history
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this service history.
	 *
	 * @return the modified date of this service history
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this service history.
	 *
	 * @param modifiedDate the modified date of this service history
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the fully qualified class name of this service history.
	 *
	 * @return the fully qualified class name of this service history
	 */
	@Override
	public String getClassName();

	public void setClassName(String className);

	/**
	 * Returns the class name ID of this service history.
	 *
	 * @return the class name ID of this service history
	 */
	@Override
	public long getClassNameId();

	/**
	 * Sets the class name ID of this service history.
	 *
	 * @param classNameId the class name ID of this service history
	 */
	@Override
	public void setClassNameId(long classNameId);

	/**
	 * Returns the class p k of this service history.
	 *
	 * @return the class p k of this service history
	 */
	@Override
	public long getClassPK();

	/**
	 * Sets the class p k of this service history.
	 *
	 * @param classPK the class p k of this service history
	 */
	@Override
	public void setClassPK(long classPK);

	/**
	 * Returns the page of this service history.
	 *
	 * @return the page of this service history
	 */
	@AutoEscape
	public String getPage();

	/**
	 * Sets the page of this service history.
	 *
	 * @param page the page of this service history
	 */
	public void setPage(String page);

	/**
	 * Returns the friendly u r l of this service history.
	 *
	 * @return the friendly u r l of this service history
	 */
	@AutoEscape
	public String getFriendlyURL();

	/**
	 * Sets the friendly u r l of this service history.
	 *
	 * @param friendlyURL the friendly u r l of this service history
	 */
	public void setFriendlyURL(String friendlyURL);

	/**
	 * Returns the portlet name of this service history.
	 *
	 * @return the portlet name of this service history
	 */
	@AutoEscape
	public String getPortletName();

	/**
	 * Sets the portlet name of this service history.
	 *
	 * @param portletName the portlet name of this service history
	 */
	public void setPortletName(String portletName);

	/**
	 * Returns the status code of this service history.
	 *
	 * @return the status code of this service history
	 */
	public int getStatusCode();

	/**
	 * Sets the status code of this service history.
	 *
	 * @param statusCode the status code of this service history
	 */
	public void setStatusCode(int statusCode);

	/**
	 * Returns the time cost of this service history.
	 *
	 * @return the time cost of this service history
	 */
	public int getTimeCost();

	/**
	 * Sets the time cost of this service history.
	 *
	 * @param timeCost the time cost of this service history
	 */
	public void setTimeCost(int timeCost);

	/**
	 * Returns the response text of this service history.
	 *
	 * @return the response text of this service history
	 */
	@AutoEscape
	public String getResponseText();

	/**
	 * Sets the response text of this service history.
	 *
	 * @param responseText the response text of this service history
	 */
	public void setResponseText(String responseText);

	/**
	 * Returns the wrapped text of this service history.
	 *
	 * @return the wrapped text of this service history
	 */
	@AutoEscape
	public String getWrappedText();

	/**
	 * Sets the wrapped text of this service history.
	 *
	 * @param wrappedText the wrapped text of this service history
	 */
	public void setWrappedText(String wrappedText);

	/**
	 * Returns the debug info of this service history.
	 *
	 * @return the debug info of this service history
	 */
	@AutoEscape
	public String getDebugInfo();

	/**
	 * Sets the debug info of this service history.
	 *
	 * @param debugInfo the debug info of this service history
	 */
	public void setDebugInfo(String debugInfo);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.liferay.portal.ext.model.ServiceHistory serviceHistory);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.liferay.portal.ext.model.ServiceHistory> toCacheModel();

	@Override
	public com.liferay.portal.ext.model.ServiceHistory toEscapedModel();

	@Override
	public com.liferay.portal.ext.model.ServiceHistory toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}