package com.liferay.portlet.trash.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.liferay.portlet.trash.model.TrashEntry;
import com.liferay.portlet.trash.service.TrashEntryLocalServiceUtil;

/**
 * The extended model base implementation for the TrashEntry service. Represents a row in the &quot;TrashEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TrashEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TrashEntryImpl
 * @see com.liferay.portlet.trash.model.TrashEntry
 * @generated
 */
public abstract class TrashEntryBaseImpl extends TrashEntryModelImpl
    implements TrashEntry {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a trash entry model instance should use the {@link TrashEntry} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            TrashEntryLocalServiceUtil.addTrashEntry(this);
        } else {
            TrashEntryLocalServiceUtil.updateTrashEntry(this);
        }
    }
}
