package com.liferay.portal.model.impl;

import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.Account;
import com.liferay.portal.service.AccountLocalServiceUtil;

/**
 * The extended model base implementation for the Account service. Represents a row in the &quot;Account_&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AccountImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AccountImpl
 * @see com.liferay.portal.model.Account
 * @generated
 */
public abstract class AccountBaseImpl extends AccountModelImpl
    implements Account {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a account model instance should use the {@link Account} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            AccountLocalServiceUtil.addAccount(this);
        } else {
            AccountLocalServiceUtil.updateAccount(this);
        }
    }
}
