package com.liferay.portal.model.impl;

import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.ClusterGroup;
import com.liferay.portal.service.ClusterGroupLocalServiceUtil;

/**
 * The extended model base implementation for the ClusterGroup service. Represents a row in the &quot;ClusterGroup&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ClusterGroupImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ClusterGroupImpl
 * @see com.liferay.portal.model.ClusterGroup
 * @generated
 */
public abstract class ClusterGroupBaseImpl extends ClusterGroupModelImpl
    implements ClusterGroup {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a cluster group model instance should use the {@link ClusterGroup} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            ClusterGroupLocalServiceUtil.addClusterGroup(this);
        } else {
            ClusterGroupLocalServiceUtil.updateClusterGroup(this);
        }
    }
}
