package com.liferay.portal.model.impl;

import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.Lock;
import com.liferay.portal.service.LockLocalServiceUtil;

/**
 * The extended model base implementation for the Lock service. Represents a row in the &quot;Lock_&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LockImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LockImpl
 * @see com.liferay.portal.model.Lock
 * @generated
 */
public abstract class LockBaseImpl extends LockModelImpl implements Lock {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a lock model instance should use the {@link Lock} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            LockLocalServiceUtil.addLock(this);
        } else {
            LockLocalServiceUtil.updateLock(this);
        }
    }
}
