package com.liferay.portal.model.impl;

import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.Portlet;
import com.liferay.portal.service.PortletLocalServiceUtil;

/**
 * The extended model base implementation for the Portlet service. Represents a row in the &quot;Portlet&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PortletImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PortletImpl
 * @see com.liferay.portal.model.Portlet
 * @generated
 */
public abstract class PortletBaseImpl extends PortletModelImpl
    implements Portlet {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a portlet model instance should use the {@link Portlet} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            PortletLocalServiceUtil.addPortlet(this);
        } else {
            PortletLocalServiceUtil.updatePortlet(this);
        }
    }
}
