package com.liferay.portal.model.impl;

import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.Release;
import com.liferay.portal.service.ReleaseLocalServiceUtil;

/**
 * The extended model base implementation for the Release service. Represents a row in the &quot;Release_&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ReleaseImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ReleaseImpl
 * @see com.liferay.portal.model.Release
 * @generated
 */
public abstract class ReleaseBaseImpl extends ReleaseModelImpl
    implements Release {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a release model instance should use the {@link Release} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            ReleaseLocalServiceUtil.addRelease(this);
        } else {
            ReleaseLocalServiceUtil.updateRelease(this);
        }
    }
}
