package com.liferay.portal.model.impl;

import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.ResourceBlock;
import com.liferay.portal.service.ResourceBlockLocalServiceUtil;

/**
 * The extended model base implementation for the ResourceBlock service. Represents a row in the &quot;ResourceBlock&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ResourceBlockImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ResourceBlockImpl
 * @see com.liferay.portal.model.ResourceBlock
 * @generated
 */
public abstract class ResourceBlockBaseImpl extends ResourceBlockModelImpl
    implements ResourceBlock {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a resource block model instance should use the {@link ResourceBlock} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            ResourceBlockLocalServiceUtil.addResourceBlock(this);
        } else {
            ResourceBlockLocalServiceUtil.updateResourceBlock(this);
        }
    }
}
