package com.liferay.portal.model.impl;

import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.ResourceAction;
import com.liferay.portal.service.ResourceActionLocalServiceUtil;

/**
 * The extended model base implementation for the ResourceAction service. Represents a row in the &quot;ResourceAction&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ResourceActionImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ResourceActionImpl
 * @see com.liferay.portal.model.ResourceAction
 * @generated
 */
public abstract class ResourceActionBaseImpl extends ResourceActionModelImpl
    implements ResourceAction {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a resource action model instance should use the {@link ResourceAction} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            ResourceActionLocalServiceUtil.addResourceAction(this);
        } else {
            ResourceActionLocalServiceUtil.updateResourceAction(this);
        }
    }
}
