package com.liferay.portal.model.impl;

import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.Subscription;
import com.liferay.portal.service.SubscriptionLocalServiceUtil;

/**
 * The extended model base implementation for the Subscription service. Represents a row in the &quot;Subscription&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SubscriptionImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SubscriptionImpl
 * @see com.liferay.portal.model.Subscription
 * @generated
 */
public abstract class SubscriptionBaseImpl extends SubscriptionModelImpl
    implements Subscription {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a subscription model instance should use the {@link Subscription} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            SubscriptionLocalServiceUtil.addSubscription(this);
        } else {
            SubscriptionLocalServiceUtil.updateSubscription(this);
        }
    }
}
