package com.liferay.portal.model.impl;

import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.Ticket;
import com.liferay.portal.service.TicketLocalServiceUtil;

/**
 * The extended model base implementation for the Ticket service. Represents a row in the &quot;Ticket&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TicketImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TicketImpl
 * @see com.liferay.portal.model.Ticket
 * @generated
 */
public abstract class TicketBaseImpl extends TicketModelImpl implements Ticket {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a ticket model instance should use the {@link Ticket} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            TicketLocalServiceUtil.addTicket(this);
        } else {
            TicketLocalServiceUtil.updateTicket(this);
        }
    }
}
