package com.liferay.portal.model.impl;

import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.Website;
import com.liferay.portal.service.WebsiteLocalServiceUtil;

/**
 * The extended model base implementation for the Website service. Represents a row in the &quot;Website&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link WebsiteImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see WebsiteImpl
 * @see com.liferay.portal.model.Website
 * @generated
 */
public abstract class WebsiteBaseImpl extends WebsiteModelImpl
    implements Website {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a website model instance should use the {@link Website} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            WebsiteLocalServiceUtil.addWebsite(this);
        } else {
            WebsiteLocalServiceUtil.updateWebsite(this);
        }
    }
}
