package com.liferay.portlet.softwarecatalog.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.liferay.portlet.softwarecatalog.model.SCProductScreenshot;
import com.liferay.portlet.softwarecatalog.service.SCProductScreenshotLocalServiceUtil;

/**
 * The extended model base implementation for the SCProductScreenshot service. Represents a row in the &quot;SCProductScreenshot&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SCProductScreenshotImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SCProductScreenshotImpl
 * @see com.liferay.portlet.softwarecatalog.model.SCProductScreenshot
 * @generated
 */
public abstract class SCProductScreenshotBaseImpl
    extends SCProductScreenshotModelImpl implements SCProductScreenshot {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a s c product screenshot model instance should use the {@link SCProductScreenshot} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            SCProductScreenshotLocalServiceUtil.addSCProductScreenshot(this);
        } else {
            SCProductScreenshotLocalServiceUtil.updateSCProductScreenshot(this);
        }
    }
}
