package com.liferay.portlet.mobiledevicerules.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.liferay.portlet.mobiledevicerules.model.MDRRule;
import com.liferay.portlet.mobiledevicerules.service.MDRRuleLocalServiceUtil;

/**
 * The extended model base implementation for the MDRRule service. Represents a row in the &quot;MDRRule&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MDRRuleImpl}.
 * </p>
 *
 * @author Edward C. Han
 * @see MDRRuleImpl
 * @see com.liferay.portlet.mobiledevicerules.model.MDRRule
 * @generated
 */
public abstract class MDRRuleBaseImpl extends MDRRuleModelImpl
    implements MDRRule {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a m d r rule model instance should use the {@link MDRRule} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            MDRRuleLocalServiceUtil.addMDRRule(this);
        } else {
            MDRRuleLocalServiceUtil.updateMDRRule(this);
        }
    }
}
