package com.liferay.portlet.expando.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.liferay.portlet.expando.model.ExpandoTable;
import com.liferay.portlet.expando.service.ExpandoTableLocalServiceUtil;

/**
 * The extended model base implementation for the ExpandoTable service. Represents a row in the &quot;ExpandoTable&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ExpandoTableImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ExpandoTableImpl
 * @see com.liferay.portlet.expando.model.ExpandoTable
 * @generated
 */
public abstract class ExpandoTableBaseImpl extends ExpandoTableModelImpl
    implements ExpandoTable {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a expando table model instance should use the {@link ExpandoTable} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            ExpandoTableLocalServiceUtil.addExpandoTable(this);
        } else {
            ExpandoTableLocalServiceUtil.updateExpandoTable(this);
        }
    }
}
