package com.liferay.portlet.social.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import com.liferay.portlet.social.model.SocialActivity;
import com.liferay.portlet.social.service.SocialActivityLocalServiceUtil;

/**
 * The extended model base implementation for the SocialActivity service. Represents a row in the &quot;SocialActivity&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SocialActivityImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SocialActivityImpl
 * @see com.liferay.portlet.social.model.SocialActivity
 * @generated
 */
public abstract class SocialActivityBaseImpl extends SocialActivityModelImpl
    implements SocialActivity {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a social activity model instance should use the {@link SocialActivity} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            SocialActivityLocalServiceUtil.addSocialActivity(this);
        } else {
            SocialActivityLocalServiceUtil.updateSocialActivity(this);
        }
    }
}
