/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portal.ext.model.impl;

import com.liferay.portal.ext.model.ModelConnectionLine;
import com.liferay.portal.ext.service.ModelConnectionLineLocalServiceUtil;
import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the ModelConnectionLine service. Represents a row in the &quot;ModelConnectionLine&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ModelConnectionLineImpl}.
 * </p>
 *
 * @author Jeff Qian
 * @see ModelConnectionLineImpl
 * @see com.liferay.portal.ext.model.ModelConnectionLine
 * @generated
 */
public abstract class ModelConnectionLineBaseImpl
	extends ModelConnectionLineModelImpl implements ModelConnectionLine {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a model connection line model instance should use the {@link ModelConnectionLine} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			ModelConnectionLineLocalServiceUtil.addModelConnectionLine(this);
		}
		else {
			ModelConnectionLineLocalServiceUtil.updateModelConnectionLine(this);
		}
	}
}